version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn package '/awsbeanstalk-tomcat8-cicd/com.webapp/'

artifacts:
  files:
    - '**/*'
base-directory: 'awsbeanstalk-tomcat8-cicd/com.webapp/'